config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 get("/hello_world", to: "welcome#hello_world")

 get "/", to: "welcome#root", as: "root"

 # root "welcome#root"

 get "/contact_us", to: "welcome#contact_us"

 post "/process_contact", to: "welcome#process_contact"



 # get "/questions/new", {to: "questions#new", as: :new_questions}
 #
 # post "/questions", {to: "questions#create", as: :questions}
 #
 # get "/questions/:id", {to: "questions#show", as: :question}
 #
 # get "/questions", {to: "questions#index"}
 #
 # get "/questions/:id/edit", {to: "questions#edit", as: :edit_question}
 #
 # patch "/questions/:id", {to: "questions#update"}
 #
 # delete "/questions/:id", {to: "questions#destroy"}

 resources :questions do
   resources :answers, only: [:create, :destroy]
 end
    resources :users, only: [:new, :create]
    resource :session, only: [:new, :create, :destroy]
end


# get 'profile', to: 'users#show'
#
# get 'profile', action: :show, controller: 'users'

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :body, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

    has_many(:answers, dependent: :destroy)
    belongs_to :user
    
    validates(:title, presence: true, uniqueness: true)
    validates(
        :body,
        presence: { message:"You have to provide body"},
        length: { minimum: 10 }
        )

    scope(:recent, -> { order(created_at: :DESC).limit(10) })
    scope(:search, -> (query) { where("title ILIKE ? OR body ILIKE ?", "%#{query}%", "%#{query}%") })
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions, dependent: :nullify
  has_many :answers, dependent: :nullify

  has_secure_password

  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
  #/questions/:question_id/answers
  @question = Question.find params[:question_id]
  @answer = Answer.new answer_params
  @answer.question = @question
   if @answer.save
     redirect_to question_path(@question)
   else
     @answers = @question.answers.order(created_at: :desc)
     render "questions/show"
   end
  end

  def destroy
   # DELETE PATH/questions/:question_id/answers/:id
    @answer = Answer.find params[:id]
    @answer.destroy
    redirect_to question_path(@answer.question)

  end


  private

  def answer_params
    params.require(:answer).permit(:body)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_question, only: [:show, :edit, :update, :destroy]

  def new
    @question = Question.new
  end

  def create

    @question=Question.new question_params
    if @question.save
      flash[:notice] = "Question Created Successfully"
      redirect_to question_path(@question)
    else
      render :new
    end
  end


  def show
    @answer = Answer.new
    @answers = @question.answers.order(created_at: :desc)
  end

  def index
    @questions = Question.all
  end

  def edit
  end

  def update
    if @question.update question_params
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def destroy
      flash[:notice] = "Question Deleted!"
      @question.destroy
      redirect_to questions_path
  end




  private

  def question_params
    params.require(:question).permit(:title, :body)
  end


  def find_question
      # get the Question with the id that's requested
      @question = Question.find params[:id]
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  end

  def destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   def new
       @user = User.new
   end
   
   def create
       @user = User.new user_params
       if @user.save
           session[:user_id] = @user.id
           flash.delete(:warning)
           redirect_to root_path
       else
           flash[:warning] = "Unable to create user"
           render :new
       end
   end

   private

   def user_params
       params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def hello_world
    render(plain: "hello_world")
  end

  def root
  end

  def contact_us
  end

  def process_contact
    # byebug

    get_name
    @email = params[:email]
    @message = params[:message]

    render :thank_you
  end

  private

  def get_name

    if params[:full_name] != ""
      @full_name = params[:full_name]
    else
      @full_name = "My Friend"
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeAnswers2020</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
    <ul class= "navbar">
      <li class = "active"><%= link_to "Home", root_path %></li>
      <li class = "active_one"><%= link_to "Contact_Us", contact_us_path %></li>
      <li class = "active_one"><%= link_to "New Question", new_question_path %></li>
      <li class = "active_one"><%= link_to "All Question", questions_path %></li>
    </ul>

    <h3 class = "topic_two"><%= flash[:notice] || flash[:alert] %></h3>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<% if @question.errors.any? %>

<ul>
  <% @question.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>




<div class="container">
  <%= form_with  model: @question, local: true do |f| %>

     <div>
       <%= f.label :title %>
       <%= f.text_field :title %>
     </div>

     <div>
       <%= f.label :body %>
       <%= f.text_area :body %>
     </div>

     <div><%= f.submit %></div>

  <% end %>
</div>

app/views/questions/edit.html.erb
<h1 class = "topic" >Question Edit Page</h1>
<%= render "form" %>

app/views/questions/index.html.erb
<h1 class = "topic">All Questions</h1>

<% @questions.each do |question| %>
<div class="container column">
  <h2><%= link_to question.title, question_path(question) %></h2>
</div>
<% end %>

app/views/questions/new.html.erb
<h1 class = "topic" >Question New Page</h1>
<%= render "form" %>

app/views/questions/show.html.erb
<div class="container">
  <h2 class = "topic_one"><%= @question.title %></h2>
  <p><%= @question.body%></p>
  <p><%= @question.created_at %></p>
  <button class="edit"><%= link_to "Edit", edit_question_path(@question) %></button>
  <button class="delete"><%= link_to "Delete", question_path(@question),
    method: :delete, data: {confirm: "Are You sure?"} %></button>
</div>

<hr>


<div class="container">
  <%= form_with(model: [@question, @answer], local: true) do |f| %>

  <% if @answer.errors.any? %>

  <ul>
    <% @answer.errors.full_messages.each do |msg| %>
    <li class="color_text"><%= msg %></li>
    <% end %>
  </ul>
  <% end %>

     <div>

       <%= f.text_area(
       :body,
       cols: 50,
       rows: 5,
       placeholder: "what are your thought?"
       ) %>

     </div>

     <div><%= f.submit "Post" %></div>

  <% end %>
</div>

<% @answers.each do |answer| %>
 <div class = "container">
    <ul>
      <li>
         <p>
            <%= answer.body%>
         </p>
         <p>
          <small>
            <button class="delete_one"><%= link_to "Delete", question_answer_path(@question, answer),
              method: :delete, data: {confirm: "Are You sure?"} %></button>
          </small>
          <small>
            Answered<%=time_ago_in_words(answer.created_at)%>
          </small>
        </p>
      </li>
    </ul>
 </div>
<% end %>

app/views/users/new.html.erb
<h1 class= "topic">User New Page</h1>
<% if @user.errors.present? %>
    <p>
        <%= @user.errors.full_messages.join(', ') %>
    </p>
<% end %>

<div class="container">
    <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
            <%= f.label :first_name %>
            <%= f.text_field :first_name %>
        </div>

        <div>
            <%= f.label :last_name %>
            <%= f.text_field :last_name %>
        </div>

        <div>
            <%= f.label :email %>
            <%= f.email_field :email %>
        </div>

        <div>
            <%= f.label :password %>
            <%= f.password_field :password%>
        </div>

        <div>
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation%>
        </div>

        <%= f.submit 'Create User' %>
    <% end %>
</div>

app/views/welcome/contact_us.html.erb
<h1 class = "topic">Contact Us</h1>
<!-- <div class="container">
  <form action="/process_contact" method="POST">

    <label for="fname">First Name</label>
    <input type="text" id="fname" name="firstname" placeholder="Your name..">

    <label for="lname">Last Name</label>
    <input type="text" id="lname" name="lastname" placeholder="Your last name..">

    <label for="country">Country</label>
    <select id="country" name="country">
      <option value="australia">Australia</option>
      <option value="canada">Canada</option>
      <option value="usa">USA</option>
    </select>

    <label for="subject">Subject</label>
    <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>

    <input type="submit" value="Submit">

  </form>
</div> -->

<div class="container">
<%= form_tag('/process_contact') do %>
   <div>
       <%= label_tag(:full_name) %><br />
       <%= text_field_tag(:full_name) %>
   </div>

   <div class = "stylebox">
       <%= label_tag(:email) %><br />
       <%= email_field_tag(:email) %>
   </div>
   <div>
       <%= label_tag(:message) %><br />
       <%= text_area_tag(:message) %>
   </div>
 <div><%= submit_tag 'Contact Us' %></div>
<% end %>

</div>

app/views/welcome/root.html.erb
<div class="bgimg">
      <div class="middle">
        <h1>WELCOME TO MY PAGE</h1>
        <hr>
      </div>
</div>

app/views/welcome/thank_you.html.erb
<div class="bgimg_one">
      <!-- <div class="middle_one">
        <h1>
          Thank You, <strong><%= @full_name %></strong>, for getting in touch
          <br>
          <strong>Your message was: </strong> <em><%= @message %></em>
          <br>
          We'll email you at: <%= @email %></h1>
      </div> -->
</div>